import streamlit as st
import pandas as pd
import pickle
import numpy as np


# Load model
with open("models/failure_prediction_model.pkl", "rb") as file:
    model = pickle.load(file)


# Page configuration
st.set_page_config(
    page_title="SmartGuard AI",
    page_icon="🤖",
    layout="centered"
)


# Title
st.title("🤖 SmartGuard AI")
st.subheader("Predictive Maintenance System")

st.write(
    """
    SmartGuard AI uses machine learning to predict possible 
    industrial equipment failures using sensor data.
    """
)


st.divider()


# Input section

st.header("Machine Sensor Inputs")


temperature = st.slider(
    "🌡️ Temperature (°C)",
    0,
    150,
    70
)


vibration = st.slider(
    "📳 Vibration Level",
    0.0,
    2.0,
    0.5
)


pressure = st.slider(
    "⚙️ Pressure",
    0,
    250,
    120
)


rpm = st.slider(
    "🔄 RPM",
    0,
    6000,
    3000
)


operating_hours = st.slider(
    "⏱️ Operating Hours",
    0,
    6000,
    2500
)


st.divider()


if st.button("🔍 Analyze Machine"):


    input_data = np.array(
        [[
            temperature,
            vibration,
            pressure,
            rpm,
            operating_hours
        ]]
    )


    prediction = model.predict(input_data)

    probability = model.predict_proba(input_data)


    failure_probability = probability[0][1] * 100

    health_score = 100 - failure_probability



    st.header("Machine Health Report")


    if prediction[0] == 1:

        st.error(
            "🔴 High Risk - Machine Failure Possible"
        )

    else:

        st.success(
            "🟢 Low Risk - Machine Healthy"
        )


    col1, col2 = st.columns(2)


    with col1:
        st.metric(
            "Failure Probability",
            f"{failure_probability:.1f}%"
        )


    with col2:
        st.metric(
            "Machine Health Score",
            f"{health_score:.1f}/100"
        )



    st.divider()


    st.subheader("AI Decision Factors")


    feature_importance = pd.DataFrame(
        {
            "Feature":[
                "Temperature",
                "Vibration",
                "Pressure",
                "RPM",
                "Operating Hours"
            ],
            "Importance":
            model.feature_importances_
        }
    )


    feature_importance = feature_importance.sort_values(
        by="Importance",
        ascending=False
    )


    st.bar_chart(
        feature_importance.set_index("Feature")
    )

    st.divider()

    st.subheader("📄 Generate Maintenance Report")

    report = f"""
SMARTGUARD AI REPORT
====================

Machine Status:
{ "FAILED RISK DETECTED" if prediction[0]==1 else "MACHINE HEALTHY" }

Failure Probability:
{failure_probability:.1f}%

Health Score:
{health_score:.1f}/100


Sensor Values:

Temperature:
{temperature} °C

Vibration:
{vibration}

Pressure:
{pressure}

RPM:
{rpm}

Operating Hours:
{operating_hours}


Recommendation:

{ "Schedule maintenance inspection immediately."
if prediction[0]==1
else "Continue monitoring machine performance." }

Generated by SmartGuard AI
"""

    st.download_button(
        label="⬇️ Download AI Report",
        data=report,
        file_name="SmartGuard_AI_Report.txt",
        mime="text/plain"
    )

st.sidebar.title("About SmartGuard AI")

st.sidebar.info(
    """
    SmartGuard AI is an ML-based predictive
    maintenance system.

    Tech Stack:

    • Python
    • Pandas
    • Scikit-learn
    • Random Forest
    • Streamlit
    """
)