import React from 'react';
import { X, Download, ShieldCheck, AlertOctagon, FileText, CheckCircle2 } from 'lucide-react';
import confetti from 'canvas-confetti';
import MagnetButton from '../ui/MagnetButton';
import { generateDiagnosticReport } from '../../lib/mlEngine';

export default function ReportModal({ isOpen, onClose, sensorValues, predictionResult }) {
  if (!isOpen) return null;

  const report = generateDiagnosticReport(sensorValues, predictionResult);

  const handleDownloadTxt = () => {
    const content = `
================================================================================
SMARTGUARD-AI INDUSTRIAL PREDICTIVE MAINTENANCE SYSTEM
OFFICIAL MACHINE CONDITION DIAGNOSTIC REPORT
================================================================================
Report ID       : ${report.reportId}
Timestamp       : ${report.timestamp}
Standard        : ${report.isoStandard}
Model Version   : ${report.modelVersion}
Cryptographic ID: ${report.signatureHash}

--------------------------------------------------------------------------------
1. EXECUTIVE DIAGNOSTIC CLASSIFICATION
--------------------------------------------------------------------------------
Machine Status      : ${report.overallStatus}
Risk Tier           : ${report.statusTier}
Failure Probability : ${report.failureProbability}
Machine Health Score: ${report.healthScore}
ML Confidence Score : ${report.confidence}

--------------------------------------------------------------------------------
2. RECORDED SENSOR TELEMETRY
--------------------------------------------------------------------------------
- Core Temperature  : ${sensorValues.temperature} °C (Threshold: 90 °C)
- Vibration Level   : ${sensorValues.vibration} mm/s (Threshold: 0.80 mm/s)
- Hydraulic Pressure: ${sensorValues.pressure} kPa (Threshold: 200 kPa)
- Rotor RPM         : ${sensorValues.rpm} RPM (Threshold: 5000 RPM)
- Operating Hours   : ${sensorValues.operating_hours} hrs (Threshold: 4000 hrs)

--------------------------------------------------------------------------------
3. ROOT CAUSE ATTRIBUTION & ACTION PROTOCOL
--------------------------------------------------------------------------------
Primary Root Cause  : ${report.rootCauseAnalysis.feature} (${report.rootCauseAnalysis.value} ${report.rootCauseAnalysis.unit})
Criticality         : ${report.rootCauseAnalysis.impact}
Recommendation      : ${report.recommendation}

================================================================================
CONFIDENTIAL & PROPRIETARY — GENERATED BY SMARTGUARD-AI
AUTHOR: Pratik Mahendra Pardeshi (AI & Machine Learning Engineer)
================================================================================
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SmartGuard_AI_Report_${report.reportId}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    // Trigger celebration if healthy
    if (!predictionResult.isFailed) {
      confetti({ particleCount: 60, spread: 60, origin: { y: 0.7 } });
    }
  };

  const handleDownloadJson = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2));
    const link = document.createElement('a');
    link.href = dataStr;
    link.download = `SmartGuard_AI_Report_${report.reportId}.json`;
    link.click();
  };

  const sensorSnapshot = [
    { label: 'Temp', value: `${sensorValues.temperature} °C`, color: 'text-cyan-700 dark:text-cyan-400' },
    { label: 'Vibration', value: `${sensorValues.vibration} mm/s`, color: 'text-amber-600 dark:text-amber-400' },
    { label: 'Pressure', value: `${sensorValues.pressure} kPa`, color: 'text-blue-600 dark:text-blue-400' },
    { label: 'RPM', value: `${sensorValues.rpm}`, color: 'text-emerald-600 dark:text-emerald-400' },
    { label: 'Hours', value: `${sensorValues.operating_hours} hrs`, color: 'text-violet-600 dark:text-violet-400' },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-neutral-900/50 dark:bg-black/70 backdrop-blur-sm">
      <div className="relative w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-white/10 p-6 md:p-8 text-neutral-900 dark:text-neutral-100 shadow-2xl">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-xl bg-neutral-100 dark:bg-white/5 border border-neutral-200 dark:border-white/10 text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white transition-colors"
          aria-label="Close report"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Certificate Header */}
        <div className="border-b border-neutral-200 dark:border-white/10 pb-5 mb-6">
          <div className="flex items-center gap-2 text-xs font-mono text-cyan-700 dark:text-cyan-400 uppercase tracking-widest mb-1">
            <FileText className="w-4 h-4" />
            <span>ISO-13374 Condition Monitoring Diagnostic Certificate</span>
          </div>
          <h2 className="text-2xl font-bold text-neutral-900 dark:text-white">
            SmartGuard-AI Telemetry Report
          </h2>
          <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-neutral-500 dark:text-neutral-400 mt-2">
            <span>ID: <strong className="text-neutral-800 dark:text-neutral-200">{report.reportId}</strong></span>
            <span>DATE: <strong className="text-neutral-800 dark:text-neutral-200">{new Date(report.timestamp).toLocaleString()}</strong></span>
          </div>
        </div>

        {/* Summary Status Box */}
        <div className={`p-4 rounded-xl border mb-6 flex flex-wrap items-center justify-between gap-4 ${
          predictionResult.isFailed
            ? 'bg-rose-50 border-rose-300 text-rose-800 dark:bg-rose-500/10 dark:border-rose-500/30 dark:text-rose-300'
            : 'bg-emerald-50 border-emerald-300 text-emerald-800 dark:bg-emerald-500/10 dark:border-emerald-500/30 dark:text-emerald-300'
        }`}>
          <div>
            <div className="text-xs font-mono uppercase font-semibold tracking-wider">
              Diagnostic Assessment
            </div>
            <div className="text-lg font-bold mt-0.5 flex items-center gap-2">
              {predictionResult.isFailed ? <AlertOctagon className="w-5 h-5 text-rose-500" /> : <ShieldCheck className="w-5 h-5 text-emerald-500" />}
              <span>{report.overallStatus}</span>
            </div>
          </div>

          <div className="flex gap-6 font-mono text-right">
            <div>
              <div className="text-[10px] text-neutral-500 dark:text-neutral-400 uppercase">Health Score</div>
              <div className="text-xl font-bold">{report.healthScore}</div>
            </div>
            <div>
              <div className="text-[10px] text-neutral-500 dark:text-neutral-400 uppercase">Failure Risk</div>
              <div className="text-xl font-bold">{report.failureProbability}</div>
            </div>
          </div>
        </div>

        {/* Telemetry Snapshot Grid */}
        <div className="mb-6">
          <div className="text-xs font-mono uppercase text-neutral-500 dark:text-neutral-400 mb-2">
            Recorded Telemetry Parameters
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
            {sensorSnapshot.map((s) => (
              <div key={s.label} className="p-2.5 rounded-lg bg-neutral-50 dark:bg-white/5 border border-neutral-200 dark:border-white/10 text-center">
                <div className="text-[10px] text-neutral-500 dark:text-neutral-400">{s.label}</div>
                <div className={`text-sm font-semibold font-mono ${s.color}`}>{s.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Action Protocol */}
        <div className="p-4 rounded-xl bg-neutral-50 dark:bg-white/5 border border-neutral-200 dark:border-white/10 mb-6">
          <div className="text-xs font-mono uppercase text-neutral-500 dark:text-neutral-400 mb-1">
            Prescribed Maintenance Action Protocol
          </div>
          <p className="text-sm text-neutral-700 dark:text-neutral-200 leading-relaxed">
            {report.recommendation}
          </p>
        </div>

        {/* Cryptographic Signature */}
        <div className="p-3 rounded-lg bg-neutral-100 dark:bg-black/40 border border-neutral-200 dark:border-white/10 font-mono text-[10px] text-neutral-500 dark:text-neutral-400 flex items-center justify-between gap-2 mb-6">
          <span className="truncate">SIG: {report.signatureHash}</span>
          <span className="text-cyan-700 dark:text-cyan-400 flex items-center gap-1 flex-shrink-0">
            <CheckCircle2 className="w-3.5 h-3.5" /> VERIFIED ML ARTIFACT
          </span>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center justify-end gap-3 pt-4 border-t border-neutral-200 dark:border-white/10">
          <MagnetButton onClick={handleDownloadJson} variant="ghost" className="text-xs py-2">
            <Download className="w-3.5 h-3.5" />
            <span>EXPORT JSON</span>
          </MagnetButton>
          <MagnetButton onClick={handleDownloadTxt} variant="primary" className="text-xs py-2">
            <Download className="w-3.5 h-3.5" />
            <span>DOWNLOAD .TXT REPORT</span>
          </MagnetButton>
        </div>
      </div>
    </div>
  );
}
